import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        clifford: {
          "50": "#fef2f2",
          "100": "#fde6e6",
          "200": "#fbd0d0",
          "300": "#f7aeae",
          "400": "#f27d7d",
          "500": "#ea5757",
          "600": "#da373d",
          "700": "#b91c1c",
          "800": "#991b1b",
          "900": "#7f1d1d",
          "950": "#450a0a",
          DEFAULT: "#da373d",
        },
        "custom-blue": {
          "50": "#f0f9ff",
          "100": "#e0f2fe",
          "200": "#b9e6fe",
          "300": "#7cd4fd",
          "400": "#36bffa",
          "500": "#1fb6ff",
          "600": "#0284c7",
          "700": "#0369a1",
          "800": "#075985",
          "900": "#0c4a6e",
          "950": "#082f49",
          DEFAULT: "#1fb6ff",
        },
        aero: {
          DEFAULT: "#5BC0EB",
        },
        "electric-indigo": {
          DEFAULT: "#5BC0EB",
        },
        "electric-purple": {
          DEFAULT: "#672BFF", //figma job
        },
        "rich-black": {
          DEFAULT: "#001514", //figma job
        },
        eggplant: {
          DEFAULT: "#4B3B47", //figma job
        },
        "chocolate-cosmos": {
          DEFAULT: "#66101F", //figma job
        },
        cream: {
          DEFAULT: "#FFFDB1", //figma job
        },
        mint: {
          DEFAULT: "#09BC8A",
          200: "#CDF9E8", //Mint green
        },
        "custom-purple": {
          "50": "#faf5ff",
          "100": "#f3e8ff",
          "200": "#e9d5ff",
          "300": "#d8b4fe",
          "400": "#c084fc",
          "500": "#a855f7",
          "600": "#9333ea",
          "700": "#7e5bef",
          "800": "#6b21a8",
          "900": "#581c87",
          "950": "#3b0764",
          DEFAULT: "#7e5bef",
        },
        "tailwind-pink": {
          "50": "#fdf2ff",
          "100": "#fae8ff",
          "200": "#f5d0fe",
          "300": "#f0abfc",
          "400": "#e879f9",
          "500": "#d946ef",
          "600": "#ff49db",
          "700": "#a21caf",
          "800": "#86198f",
          "900": "#701a75",
          "950": "#4a044e",
          DEFAULT: "#ff49db",
        },
        "custom-pink": {
          DEFAULT: "#DB324D",
        },
        auburn: {
          DEFAULT: "#A62639",
        },
        rojo: {
          DEFAULT: "#DE1A1A",
        },
        "persian-red": {
          DEFAULT: "#C3423F",
        },
        "custom-orange": {
          "50": "#fff7ed",
          "100": "#ffedd5",
          "200": "#fed7aa",
          "300": "#fdba74",
          "400": "#fb923c",
          "500": "#ff7849",
          "600": "#ea580c",
          "700": "#c2410c",
          "800": "#9a3412",
          "900": "#7c2d12",
          "950": "#431407",
          DEFAULT: "#ff7849",
        },
        "custom-green": {
          "50": "#f0fdf4",
          "100": "#dcfce7",
          "200": "#bbf7d0",
          "300": "#86efac",
          "400": "#4ade80",
          "500": "#13ce66",
          "600": "#16a34a",
          "700": "#15803d",
          "800": "#166534",
          "900": "#14532d",
          "950": "#052e16",
          DEFAULT: "#13ce66",
        },
        "custom-yellow": {
          "50": "#fefce8",
          "100": "#fef9c3",
          "200": "#fef08a",
          "300": "#fde047",
          "400": "#ffc82c",
          "500": "#eab308",
          "600": "#ca8a04",
          "700": "#a16207",
          "800": "#854d0e",
          "900": "#713f12",
          "950": "#422006",
          DEFAULT: "#ffc82c",
        },
        "selective-yellow": {
          DEFAULT: "#fdb20b",
        },
        melon: {
          "50": "#F8D4C9",
          "100": "#F6C4B7",
          "500": "#E55934",
          DEFAULT: "#E55934",
        },
        gray: {
          "50": "#f9fafb",
          "100": "#f3f4f6",
          "200": "#e5e7eb",
          "300": "#d1d5db",
          "400": "#9ca3af",
          "500": "#8492a6",
          "600": "#4b5563",
          "700": "#374151",
          "800": "#1f2937",
          "900": "#111827",
          "950": "#030712",
          DEFAULT: "#8492a6",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      fontFamily: {
        roboto: ["Roboto", "sans-serif"],
        geistSans: ["Geist Sans", "sans-serif"],
        aBeeZee: ["ABeeZee", "serif"],
        istokWeb: ["Istok Web", "serif"],
        onest: ["Onest", "serif"],
        poiretOne: ["Poiret One", "serif"],
        lexend: ["Lexend", "serif"],
        "echo-deco": ["Echo Decorative", "sans-serif"],
        "neon-club-music": ["Neon Club Music", "sans-serif"],
        "segdwick-ave-display": ["Segdwick Ave Display", "sans-serif"],
        "dm-sans": ["DM Sans", "sans-serif"],
        "merriweather-sans": ["Merriweather Sans", "sans-serif"],
        merriweather: ["Merriweather", "serif"],
        rimouski: ["Rimouski", "Corben", "Arial", "sans-serif", "sans-serif"],
        "rimouski-sb": [
          "Rimouski",
          "Corben",
          "Arial",
          "sans-serif",
          "sans-serif",
        ],
        wavefont: ["Wavefont", "sans-serif"],
        montserrat: ["Montserrat", "sans-serif"],
        jost: ["Jost", "sans-serif"],
        corben: ["Corben", "sans-serif"],
        caudex: ["Caudex", "serif"],
        cabin: ["Cabin", "serif"],
        allan: ["Allan", "serif"],
        "cherry-cream-soda": ["Cherry Cream Soda", "cursive"],
        brawler: ["Brawler", "serif"],
        "bebas-neue": ["Bebas Neue", "cursive"],
        bentham: ["Bentham", "serif"],
      },
      keyframes: {
        "chromatic-offset": {
          "0%": {
            textShadow: "1px 0 0 #DB324D, -1px 0 0 #5BC0EB",
          },
          "100%": {
            textShadow: "-1px 0 0 #DB324D, 1px 0 0 #5BC0EB",
          },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
